backend:
  name: git-gateway

media_folder: "site/static/uploads" # Folder where user uploaded files should go
public_folder: "uploads"

collections:
  - label: "Posts"
    name: "posts"
    folder: "site/content/posts"
    create: true
    sort: "date:desc"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Post Date", name: "date", widget: "datetime", format: "MMM Do YY"}
      - {label: "Published", name: "published", widget: "boolean", {default: true}}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Intro", name: "intro", widget: "text"}
      - {label: "Content", name: "body", widget: "markdown"}
      - label: "Testimonials"
        name: "testimonials"
        widget: "list"
        fields:
          - {label: Quote, name: quote, widget: string, default: "Everything is awesome!"}
          - label: Author
            name: author
            widget: object
            fields:
              - {label: Name, name: name, widget: string, default: "Emmet"}
              - {label: Avatar, name: avatar, widget: image, default: "/img/emmet.jpg"}

