backend:
  name: git-gateway

media_folder: "site/static/uploads" # Folder where user uploaded files should go
public_folder: "uploads"

collections:
  - label: "Posts"
    name: "posts"
    folder: "site/content/posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Content", name: "body", widget: "markdown"}
